### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by w1tw0lf** [custom-components/sensor.unifigateway#35]
Getting an error, "Failed to connect to Unifi Security Gateway: Login failed - status code: 401"

cloudkey v2+, firmware: 2.1.4
controller version: 6.1.71

sensor config:
  - platform: unifigateway
     host: x.x.x.x
     username: 
     password: 
     version: unifiOS

If I remove, version: unifiOS it gives me and status code: 404

**Comment by holblin** [comment]
This is probably the same root cause as https://github.com/custom-components/sensor.unifigateway/issues/17

**Comment by w1tw0lf** [comment]
Followed what was posted here, https://github.com/finish06/pyunifi/issues/62 and fixed my login issue. All seems to work as needed now.

**Comment by ahmaddxb** [comment]
@w1tw0lf could you explain a little more what need to be done, which file do we have to edit and where is it located? Thanks

**Comment by w1tw0lf** [comment]
Running Home Assistant Supervised on Debian.
ssh into debian and run `sudo find . -name "controller.py"` to find the file.
edit file in these location as I wasn't sure which one:
`/var/lib/docker/overlay2/e53d3151147f8ba44837d0a1b453280fe79636b4d4ba8a64a1d58f13636d4705/diff/usr/local/lib/python3.8/site-packages/pyunifi/controller.py`
`/var/lib/docker/overlay2/6b2bd4a16684ba5e4af1b5787bc28bb9be5a17fc7562714afee7523a5a948b16/diff/usr/src/homeassistant/homeassistant/components/unifi/controller.py`

Not sure if your locations will be the same.

**Comment by ahmaddxb** [comment]
Im running home assistant from proxmox virtual machine .qcow2 image

**Comment by ahmaddxb** [comment]
could you post your controller.py file so i can replace it with mine to test if it works

**Comment by w1tw0lf** [comment]
unzip the attached
[controller.zip](https://github.com/custom-components/sensor.unifigateway/files/6205572/controller.zip)

**Comment by holblin** [comment]
Hi, does anyone could help me to change the file? I'm running HA on a Raspberry Pi with the official image.
I don't know how to access the files in that case.

**Comment by holblin** [comment]
Ok I think I got it. For the steps:
- Install addon `SSH & Web Terminal`
- Configure a password / ssh key
- Disable the `Protection mode`
- Start / Restart the addon
- Open the web UI of  `SSH & Web Terminal`
- Enter into homeassistant container: `docker exec -it homeassistant /bin/bash`
- Go to the correct folder: `cd /usr/local/lib/python3.8/site-packages/pyunifi`
- Copy the file for backup: `cp controller.py controller.back.py`
- Edit the file and save it: `vi controller.py`
- Quit the editor / docker: `exit`
- Restart home assistant (core only?)
- Check your core logs :-)

**Comment by ahmaddxb** [comment]
Did it the only error i get not is 

Logger: custom_components.unifigateway.sensor
Source: custom_components/unifigateway/sensor.py:142
Integration: unifigateway (documentation)
First occurred: 11:54:03 (2 occurrences)
Last logged: 11:55:03

Failed to access alerts info: Expecting value: line 1 column 1 (char 0)

**Comment by holblin** [comment]
Yes I have the same @ahmaddxb , I didn't took time to dig it more :-)

**Comment by jchasey** [comment]
If somebody with a Gen2 Plus wants to do a pull request to incorporate the changes happy to merge.

**Comment by holblin** [comment]
@jchasey the problem is in the dependency https://github.com/finish06/pyunifi/
This has been already fixed under their development branch but they didn't release it (https://github.com/finish06/pyunifi/tree/development).
I ask to make a new release but I don't think the repo is highly active (last change 8 months ago): https://github.com/finish06/pyunifi/issues/62#issuecomment-805992391

For the custom component, the options are limited:
- Wait they release a new version
- Fork the lib and publish it under a new name
- Bundle the development branch of the lib within the custom component until they release the new version.
- Not use the lib and reimplement the feature within the component

**Comment by w1tw0lf** [comment]
Still having the same issue on v0.3.3. The previous fix doesn't seem to work any more.

**Comment by jchasey** [comment]
This should have bumped to the latest PyUnifi build, updated yesterday which allegedly fixes the issue.

**Comment by w1tw0lf** [comment]
did the update, rebooted and failed with same issue as initially posted. The manually pulled the controller.py 2.21 into /usr/local/lib/python3.8/site-packages/pyunifi/ and gave me error 401 login issue.

**Comment by jamieshaw** [comment]
> did the update, rebooted and failed with same issue as initially posted. The manually pulled the controller.py v2.21 into /usr/local/lib/python3.8/site-packages/pyunifi/ after connecting to the homeassistant docker and gave me error 401 login issue.

Same here — just updated to 0.3.3 — endpoint returns 401 during login for Home Assistant specific user configured as "Limited Admin" with "Read Only" permissions for UniFi Network.

UCK2+ — v2.0.24
UniFi Controller — 6.1.71

**Comment by w1tw0lf** [comment]
> > did the update, rebooted and failed with same issue as initially posted. The manually pulled the controller.py v2.21 into /usr/local/lib/python3.8/site-packages/pyunifi/ after connecting to the homeassistant docker and gave me error 401 login issue.
> 
> ~Same here — just updated to 0.3.3 — UCK2+ endpoint returns 401 during login for Home Assistant specific user configured as "Limited Admin" with "Read Only" permissions for UniFi Network.~
> 
> **EDIT**
> Scratch that — I can confirm it works correctly when configuring the version as `UDMP-unifiOS`.

Thank you, fixed for me as well after changing from 'unifios' to 'UDMP-unifiOS'
